### ISSUE TITLE
Update Checkbox/Radio styles to match new styles found on Shop & Enroll

### ISSUE THREAD

**Issue by mrtrimble** [ritterim/platform-ui#824]
## 🔧 Enhancement Request 
We are now using new styling for checkbox and radio inputs on Shop & Enroll, these styles should be our new standard within Platform UI.

Codepen demo of styles:
https://codepen.io/mrtrimble/pen/WNYGYoa/5f495acdc71b394c2ba09f3b04f70d84

Once these changes are included in Platform UI, we can then update in other RitterIM associated sites.

## Who is asking for the feature?
Frontend / @mrtrimble 

## What business problem is this hoping to solve?
Better consistency across all sites / products

**Comment by hougasian** [comment]
reminder: anything other than a patch needs a label applied on the PR
<img width="308" alt="Screenshot 2023-10-05 at 7 56 44 AM" src="https://github.com/ritterim/platform-ui/assets/6231956/ccb89613-18f0-4611-80e3-9f34fec34281">

**Comment by tedk13** [comment]
There's a lot of conversation here based on checkboxes in the other repos but, since we're doing the 2.0 stuff I'm thinking this should just be closed. Thoughts, @hougasian @mrtrimble
