### ISSUE TITLE
implement pagefind

### ISSUE THREAD

**Issue by hougasian** [ritterim/platform-ui#831]
## 🔧 Enhancement Request 

implement pagefind as a search engine for platform UI.

## Who is asking for the feature?

@hougasian @mrtrimble 

## What business problem is this hoping to solve?

search

**Comment by chelsealundy** [comment]
@mrtrimble  is this an agent faced website? Do you have a URL For QA to test it on?

**Comment by mrtrimble** [comment]
@chelsealundy - not necessarily agent facing, but this is a public website - can be accessed here: https://platformui.com/

This is issue was to add search functionality to the site, so it can be tested by:
- Browse to https://platformui.com/
- Click on the `Search Docs` button in the upper-right corner of the page
- In the search modal, search for things like `accordion`, `button`, or `modal`

While writing this comment, I realized I did not account for the mobile view when I added this - I will fix that shortly... lol

**Comment by mrtrimble** [comment]
Fixed mobile issue here: https://github.com/ritterim/pui-website/pull/326

**Comment by chelsealundy** [comment]
Verified on Dev: 

This is snazzy!! I also confirmed it is hidden for mobile. 

<details> 

![image](https://github.com/ritterim/platform-ui/assets/13785287/1fcb605e-7ca3-4518-8425-b7b7ebea0986)

</details>
