### ISSUE TITLE
[PUI 2.0] Inception/Research a PUI reset

### ISSUE THREAD

**Issue by tedk13** [ritterim/platform-ui#854]
## 🔧 Enhancement Request 

There are a lot of CSS reset options available. The team should do some research to find one that works best even if that means building our own. Whether that be from scratch or piecing together a camel-like reset based on other options available. 

## Who is asking for the feature?
PUI Core team

**Comment by mrtrimble** [comment]
Worked with @tedk13 to research and review CSS resets, added to PUI 2.0 branch in PR:
https://github.com/ritterim/platform-ui/pull/855
